#!/bin/bash

DAEMON_NAME=sniffer

DAEMON="/home/mr_nachtigal/projects/sniff_last/output/sniffer" #change this to dynamic

PIDFILE=/var/run/$DAEMON_NAME.pid

stop() {
    if [[ -f $PIDFILE ]]; then
        pid=$(cat $PIDFILE)
        if [[ -n $pid ]]; then
            kill $pid
            echo "Daemon stopped."
        fi
    fi
}

start() {
    if [[ -f $PIDFILE ]]; then
        echo "Daemon already running."
        exit 1
    fi

    $DAEMON &
    echo $! > $PIDFILE
    echo "Daemon started."
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0